name: Deploy my lambda function
on:
  push:
    branches: 
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: echo Hello from Action 1
        run: echo 'Hello from Action1'
      - name: echo Hello from Action2
        run: echo 'Hello from Action2'
      